### ISSUE TITLE
Import failed for rtandroid.jar file

### ISSUE THREAD

**Issue by smallccn** [RTAndroid/android_packages_app_Sample#1]
Hello sir,

I've tried to load your rdandroid.jar file into my own project to to enable root permission for my app, but it can't be loaded successfully because the jdk version is not same.

could you please update the source code for rtandroid.jar file?

Thanks.
smallc.

**Comment by ikalkov** [comment]
Is your app running on RTAndroid? If yes, just compile it with Java 7. If not, there is no way you can use the library as it relies on system services not available in other Android distributions.
